PUCUniversityManagementSystem/Models/StudentResult.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem.Models
{
    public class StudentResult
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please select a student Registration No!")]
        [DisplayName("Student Reg No.")]
        public int StudentId { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
       
        public int  CourseId  { get; set; }
       
        public string Grade { get; set; }
        public bool Status { get; set; }
    }
}

PUCUniversityManagementSystem/Models/StudentResultViewModel.cs
namespace UniversityManagementSystem.Models
{
    public class StudentResultViewModel
    {
        public int StudentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }

    }
}

PUCUniversityManagementSystem/Controllers/StudentResultController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class StudentResultController : Controller
    {
        StudentManager studentManager=new StudentManager();
        CourseManager courseManager=new CourseManager();
        
        // GET: /StudentResult/Create
        public ActionResult Save()
        {
            IEnumerable<Student> students = studentManager.GetAll;
            IEnumerable<Course> courses = courseManager.GetAll;
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }

        //
        // POST: /StudentResult/Create
        [HttpPost]
        public ActionResult Save(StudentResult studentResult)
        {
            try
            {
                ViewBag.alart = studentManager.Save(studentResult);
                IEnumerable<Student> students = studentManager.GetAll;
                IEnumerable<Course> courses = courseManager.GetAll;
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
                //return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                ViewBag.alart = exception.InnerException.Message;
                return View();
            }
        }


        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student= studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCoursesTakebByStudent(int studentId)
        {
            IEnumerable<Course> courses = courseManager.GetCoursesTakenByaStudentById(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ViewStudentResult()
        {
            IEnumerable<Student> students = studentManager.GetAll;
            ViewBag.Students = students;
            return View();
        }

        public JsonResult GetStudentResultByStudentId(int studentId)
        {
            IEnumerable<StudentResultViewModel> studentResults = studentManager.GetStudentResultByStudentId(studentId);
            return Json(studentResults, JsonRequestBehavior.AllowGet);
        }
        

    }
}

PUCUniversityManagementSystem/Views/StudentResult/Save.cshtml
@using UniversityManagementSystem.Models
@model UniversityManagementSystem.Models.StudentResult
@{
    ViewBag.Title = "Add Student Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
    AlartType alartType = ViewBag.alart;
}


<div class="col-sm-4"></div>
<div class="col-sm-4" style="padding-top: 30px">
    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center"><h4><strong>Save Student Result</strong></h4></div>
        <div class="panel-body">
            <div>
                <form id="saveStudentResult" method="POST">


                    @if (ViewBag.alart != null)
                    {
                        <div class="alert alert-@alartType.Type">@alartType.Message</div>

                    }




                    <div>
                        <table class="form-group">
                            <tr>

                                <td>
                                    @Html.LabelFor(s => s.StudentId)
                                </td>
                                <td>
                                    <select id="StudentId" name="StudentId" class="form-control">
                                        <option value="">..Select..</option>
                                        @foreach (var student in ViewBag.Students)
                                        {
                                            <option value="@student.Id">@student.RegNo</option>
                                        }
                                    </select>
                                    <br />
                                </td>

                            </tr>

                            <tr>
                                <td>
                                    <label for="Name">Name</label>
                                </td>
                                <td>
                                    <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" />
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="Email">Email</label>
                                </td>
                                <td>
                                    <input type="text" id="Email" class="form-control" name="Email" readonly="readonly" />
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="Department">Department</label>
                                </td>
                                <td>
                                    <input type="text" id="Department" class="form-control" name="Department" readonly="readonly" />
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="CourseId">Course</label>
                                </td>
                                <td>
                                    <select id="CourseId" name="CourseId" class="form-control">
                                        <option value="">..Select..</option>
                                    </select>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label for="Grade">Grade</label>
                                </td>
                                <td>
                                    <select id="Grade" name="Grade" class="form-control">
                                        <option value="">Select Grade</option>
                                        <option value="A+">A+</option>
                                        <option value="A">A</option>
                                        <option value="A-">A-</option>
                                        <option value="B+">B+</option>
                                        <option value="B">B</option>
                                        <option value="B-">B-</option>
                                        <option value="C+">C+</option>
                                        <option value="C">C</option>
                                        <option value="C-">C-</option>
                                        <option value="D+">D+</option>
                                        <option value="D">D</option>
                                        <option value="D-">D-</option>
                                        <option value="F">F</option>
                                    </select>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <input type="submit" value="Save" class="btn btn-success btn-block" />
                                </td>
                            </tr>
                        </table>
                    </div>
                </form>
            </div>
        </div>
        </div>
        </div>
        
        @section scripts{
            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script>
                $(document).ready(function () {
                    $("#saveStudentResult").validate({
                        rules: {
                            StudentId: "required",
                            CourseId: "required",
                            Grade: "required"
                        },
                        messages: {
                            StudentId: "Please select the student reg no",
                            CourseId: "Please select a course",
                            Grade: "Please select grade"
                        }
                    });




                    $("#StudentId").change(function () {
                        var stId = $("#StudentId").val();
                        $("#CourseId").empty();
                        $("#CourseId").append('<option value="">Select Course</option>');

                        var json = { studentId: stId };

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetStudentById", "StudentResult")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {
                                //alert(data);

                                var name = data.Name;
                                var email = data.Email;
                                var dept = data.Department;
                                $("#Name").val(name);
                                $("#Email").val(email);
                                $("#Department").val(dept);
                            }
                        });


                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetCoursesTakebByStudent", "StudentResult")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {


                                $.each(data, function (key, value) {
                                    //alert(key);
                                    $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                                });
                            }
                        });

                    });

                });
            </script>
        }

PUCUniversityManagementSystem/Views/StudentResult/ViewStudentResult.cshtml
@using System
@{
    ViewBag.Title = "Student Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script language="javascript">


    function myPrint() {
        var myPrintContent = document.getElementById('printDIV');
        var myPrintWindow = window.open('left=300,top=100,width=400,height=400');
        myPrintWindow.document.write(myPrintContent.innerHTML);
        myPrintWindow.document.getElementById('hiddenDiv').style.display = 'block';
        myPrintWindow.document.close();
        myPrintWindow.focus();
        myPrintWindow.print();
        myPrintWindow.close();
        return false;
    }
</script>


<div class="col-sm-4"></div>
<div class="col-sm-4" style="padding-top: 30px">

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center"><h4><strong>Student Result</strong></h4></div>
        <div class="panel-body">

            <div>
                <form id="viewStudentResult">

                    <table class="form-group">
                        <tr>
                            <td>
                                <label for="StudentId">Registration No:  </label>
                            </td>
                            <td>
                                <select id="StudentId" name="StudentId" class="form-control">
                                    <option value="">..Select..</option>
                                    @foreach (var student in ViewBag.Students)
                                    {
                                        <option value="@student.Id">@student.RegNo</option>
                                    }
                                </select>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="Name">Name: </label>
                            </td>
                            <td>
                                <input type="text" id="Name" name="Name" class="form-control" readonly="readonly" />
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="Email">Email: </label>
                            </td>
                            <td>
                                <input type="text" id="Email" name="Email" class="form-control" readonly="readonly" />
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="Department">Department: </label>
                            </td>
                            <td>
                                <input type="text" id="Department" name="Department" class="form-control" readonly="readonly" />
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>

                                <input type="submit" class="btn btn-success btn-block" value="Make PDF" onclick="myPrint();" />
                                <br />
                            </td>
                        </tr>
                    </table>
                    
                </form>
            </div>


        </div>
        </div>

        </div>
<div class="col-sm-4"></div>
<div>
    @*<div class="col-sm-2"></div>*@
    <div class="col-sm-10" align="center">
        <div id="studenRsult">
            <div id="printDIV">
                <div id="hiddenDiv" align="center" style="display: none">
                    <table width="90%" style="margin-bottom: 25px;">
                        <tr>
                            @*<td></td>*@
                            <td style="padding-left: 250px"><img src="~/images/puc.jpg" style="padding-left: 250px; width: 120px; height: 90px; border-radius: 25px 0px;"/>

                            </td>
                        </tr>
                        <tr align="center">
                            <td><h2>PUC University Chittagong</h2></td>
                        </tr>
                    </table>
                    <h3 style="text-align: center; background-color: #9AD9EA; padding: 5px 10px; color: black; border-radius: 10px;">Academic Transcript</h3>
                    <table style="width: 90%">
                        <tr>
                            <td width="30%"><b>Name:</b> </td>
                            <td width="70%"><label id="printName" style="font-weight: bold; "></label></td>
                        </tr>
                        <tr>
                            <td><b>Registration No:</b></td>
                            <td><label id="printRegNo"></label></td>
                        </tr>
                        <tr>
                            <td><b>Email:</b></td>
                            <td><label id="printEmail"></label></td>
                        </tr>

                        <tr>
                            <td><b>Contact No:</b></td>
                            <td><label id="printContact"></label></td>
                        </tr>
                        <tr>
                            <td><b>Department:</b></td>
                            <td><label id="printDepartment"></label></td>
                        </tr>
                    </table>
                    <br />
                    <br />
                    <table class="table table-bordered" style="border: 1px solid black; width: 100%; border-collapse: collapse; margin-bottom: 100px;">
                        <tr>
                            <th class="warning" style="border: 1px solid black;">Code</th>
                            <th class="danger" style="border: 1px solid black;">Name</th>
                            <th class="success" style="border: 1px solid black;">Grade</th>
                        </tr>
                        <tbody id="myDataPrint"></tbody>
                    </table>
                    <table width="90%">
                        <tr>
                            <td><p style="text-align: left;">Date  of Publication: @DateTime.Now.ToString("dd-MMM-yyyy")</p></td>
                            <td><h4 style="text-align: right;">Controller of Examination</h4></td>
                        </tr>
                    </table>
                </div>
            </div>
            <table class="table table-bordered" style="border: 1px solid black; width: 100%; border-collapse: collapse;">
                <caption style="font-size: 30px; font-weight: bolder; margin-bottom: 20px">Result</caption>
                <tr>
                    <th class="warning" style=" border: 1px solid black; ">Code</th>
                    <th class="danger" style="border: 1px solid black;">Name</th>
                    <th class="success" style="border: 1px solid black;">Grade</th>
                </tr>
                <tbody id="myData"></tbody>
            </table>
        </div>
    </div>
    @*<div class="col-sm-2"></div>*@
</div>

        
        @section scripts{
            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script>
                $(document).ready(function () {
                    $("#StudentId").change(function () {
                        var stId = $("#StudentId").val();

                        $("#myData").empty();
                        var json = { studentId: stId };

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetStudentById", "StudentResult")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {
                                //alert(data);

                                var name = data.Name;
                                var email = data.Email;
                                var dept = data.Department;
                                var regNo = data.RegNo;
                                var contactNo = data.Contact;

                                $("#Name").val(name);
                                $("#Email").val(email);
                                $("#Department").val(dept);
                                $("#printName").text(name);
                                $("#printEmail").text(email);
                                $("#printDepartment").text(dept);
                                $("#printRegNo").text(regNo);
                                $("#printContact").text(contactNo);

                            }
                        });


                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetStudentResultByStudentId", "StudentResult")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {

                                var i = 0;

                                $.each(data, function (index, value) {

                                    var row = $("<tr><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Code + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Name + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Grade + "</td></tr>");
                                    $("#myData").append(row);
                                    var row2 = $("<tr><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Code + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Name + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Grade + "</td></tr>");
                                    $("#myDataPrint").append(row2);

                                });
                            }
                        });

                    });

                });
            </script>
        }