PUCUniversityManagementSystem/Models/EnrollStudentInCourse.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem.Models
{
    public class EnrollStudentInCourse
    {
        public int Id { get; set; }
        [DisplayName("Registration No")]
        public int StudentId { get; set; }
        
        public string Name { get; set; }
        public string Email { get; set; }
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
        [DisplayName("Course")]
        public int CourseId { get; set; }
        [DataType(DataType.Date)]
        public DateTime EnrollDate { get; set; }

        public bool Status { get; set; }
    }
}

PUCUniversityManagementSystem/Controllers/EnrollStudentInCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class EnrollStudentInCourseController : Controller
    {
        StudentManager studentManager=new StudentManager();
        CourseManager courseManager=new CourseManager();
        
        [HttpGet]
        public ActionResult Enroll()
        {
            IEnumerable<Student> students = studentManager.GetAll;
            IEnumerable<Course> courses = courseManager.GetAll;
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }
        [HttpPost]
        public ActionResult Enroll(EnrollStudentInCourse enrollStudent)
        {
            string message;
            try
            {
                ViewBag.alart = studentManager.Save(enrollStudent);
                IEnumerable<Student> students = studentManager.GetAll;
                IEnumerable<Course> courses = courseManager.GetAll;
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
            }
            catch (Exception exception)
            {

               message= exception.InnerException.Message;
               ViewBag.alart = message;
                return View();
            }
        }

        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student = studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseByStudentId(int studentId)
        {
            Student aStudent = studentManager.GetAll.ToList().Find(st => st.Id == studentId);
            IEnumerable<Course> courses = courseManager.GetAll.ToList().FindAll(d => d.DepartmentId == aStudent.DepartmentId);
            return Json(courses, JsonRequestBehavior.AllowGet);

        }

	}
}

PUCUniversityManagementSystem/Views/EnrollStudentInCourse/Enroll.cshtml
@using UniversityManagementSystem.Models
@{
    ViewBag.Title = "Enroll Student In a Course";
    Layout = "~/Views/Shared/_Layout.cshtml";
    AlartType alartType = ViewBag.alart;
}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

<div class="col-sm-4"></div>
<div class="col-sm-4" style="padding-top: 30px">

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center"><h4><strong>Enroll In a Course</strong></h4></div>
        <div class="panel-body">

            <div>

                <form id="enrollCourse" method="POST">

                    @if (ViewBag.alart != null)
                    {
                        <div class="alert alert-@alartType.Type">@alartType.Message</div>

                    }

                    <div class="form-group">
                        <label for="StudentId">Registration No</label>
                        <select id="StudentId" name="StudentId" class="form-control">
                            <option value="">Select....</option>
                            @foreach (var student in ViewBag.Students)
                            {
                                <option value="@student.Id">@student.RegNo</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" readonly="readonly" name="Name" placeholder="This Field Is Read Only">
                    </div>
                    <div class="form-group">
                        <label for="Email">Email</label>
                        <input type="text" class="form-control" id="Email" readonly="readonly" name="Email" placeholder="This Field Is Read Only">
                    </div>
                    <div class="form-group">
                        <label for="DepartmentId">Department</label>
                        <input type="text" class="form-control" id="DepartmentId" name="DepartmentId" readonly="readonly" placeholder="This Field Is Read Only" />
                    </div>
                    <div class="form-group">
                        <label for="CourseId">Course</label>
                        <select id="CourseId" name="CourseId" class="form-control">
                            <option value="">Select....</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="EnrollDate">Date</label>
                        <input type="date" class="form-control" id="EnrollDate" name="EnrollDate" value="@DateTime.Now.ToShortDateString()">
                    </div>

                    <button type="submit" class="btn btn-success btn-block">Enroll</button>
                </form>
            </div>

        </div>
</div>

            

        </div>
        <div class="col-sm-4"></div>



        @section scripts{


            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery-ui.js"></script>
            <script>
                $(document).ready(function () {
                $('#EnrollDate').datepicker();

                    $("#enrollCourse").validate({
                        rules: {
                            StudentId: "required",
                            CourseId: "required",
                            EnrollDate: "required"
                        },
                        messages: {
                            StudentId: "Please select student Registration No",
                            CourseId: "Please select Course",
                            EnrollDate: "Select the date"
                        }
                    });

                    $("#StudentId").change(function () {
                        var stId = $("#StudentId").val();
                        $("#CourseId").empty();
                        var json = { studentId: stId };

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetStudentById", "EnrollStudentInCourse")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {
                                //alert(data);

                                var name = data.Name;
                                var email = data.Email;
                                var dept = data.Department;
                                $("#Name").val(name);
                                $("#Email").val(email);
                                $("#DepartmentId").val(dept);
                            }
                        });


                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetCourseByStudentId", "EnrollStudentInCourse")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {


                                $.each(data, function (key, value) {
                                    //alert(key);
                                    $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                                });
                            }
                        });

                    });
                });
            </script>
        }