PUCUniversityManagementSystem/Models/CourseAssignToTeacher.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem.Models
{
    public class CourseAssignToTeacher
    {
        public int Id { get; set; }
        [DisplayName("Department")]
        [Required]
        public int DepartmentId { get; set; }
        [DisplayName("Teacher")]
        [Required]
        public int TeacherId { get; set; }
        [DisplayName("Credit To be Taken")]
        public float CreditTobeTaken { get; set; }
          [Required]
        [DisplayName("Remaining Credit")]
        public float CreditTaken { get; set; }
          [Required]
        [DisplayName("Course")]
        public int CourseId { get; set; }
         [Required]
        public string Name { get; set; }
         [Required]
        public float Credit { get; set; }
        public bool Status { get; set; }
    }
}

PUCUniversityManagementSystem/Controllers/CourseAssignToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseAssignToTeacherController : Controller
    {
        CourseManager courseManger = new CourseManager();
        DepartmentManager departmentManager = new DepartmentManager();
        TeacherManager teacherManager = new TeacherManager();
        CourseAssignToTeacherManager courseAssignToTeacherManager=new CourseAssignToTeacherManager();
        public ActionResult AssignCourseToTeacher()
        {
            IEnumerable<Course> courses = courseManger.GetAll;
            IEnumerable<Department> departments = departmentManager.GetAll();
            IEnumerable<Teacher> teachers = teacherManager.GetAll;
            ViewBag.Courses = courses;
            ViewBag.Departments = departments;
            ViewBag.Teachers = teachers;
            return View();
        }
        [HttpPost]
        public ActionResult AssignCourseToTeacher(CourseAssignToTeacher courseAssign)
        {
            try
            {
                ViewBag.alart = courseAssignToTeacherManager.Save(courseAssign);
                IEnumerable<Course> courses = courseManger.GetAll;
                IEnumerable<Department> departments = departmentManager.GetAll();
                IEnumerable<Teacher> teachers = teacherManager.GetAll;
                ViewBag.Courses = courses;
                ViewBag.Departments = departments;
                ViewBag.Teachers = teachers;
                return View();
            }
            catch (Exception exception)
            {
                if (exception.InnerException != null)
                    ViewBag.alart = new AlartType((exception.InnerException.Message),"danger");
                return View();
            }
        }

        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {

            IEnumerable<Teacher> teachers = teacherManager.GetAll;
            var teacherList = teachers.ToList().FindAll(t => t.DepartmentId == departmentId);
            return Json(teacherList, JsonRequestBehavior.AllowGet);


        }

        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            IEnumerable<Course> courses = courseManger.GetAll;
            var courseList = courses.ToList().FindAll(c => c.DepartmentId == departmentId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherById(int teacherId)
        {
            IEnumerable<Teacher> teachers = teacherManager.GetAll;
            Teacher aTeacher = teachers.ToList().Find(t => t.Id == teacherId);
            return Json(aTeacher, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseById(int courseId)
        {
            IEnumerable<Course> courses = courseManger.GetAll;
            Course aCourse = courses.ToList().Find(c => c.Id == courseId);
            return Json(aCourse, JsonRequestBehavior.AllowGet);
        }
	}
}

PUCUniversityManagementSystem/Views/CourseAssignToTeacher/AssignCourseToTeacher.cshtml
@using UniversityManagementSystem.Models
@{
    ViewBag.Title = "Assign Course to Teacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
    AlartType alartType = ViewBag.alart;
}
<div class="col-sm-4"></div>
<div class="col-sm-4" style="padding-top: 30px">


    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading" style="text-align: center"><h4><strong>Course Assign To Teacher</strong></h4></div>
        <div class="panel-body">

            <div>

                <form id="courseAssignToteacher" method="POST">


                    @if (ViewBag.alart != null)
                    {
                         <div class="alert alert-@alartType.Type">@alartType.Message</div>

                    }


                    <table class="form-group">
                        <tr>
                            <td>
                                <label for="DepartmentId">Department</label>
                            </td>
                            <td>
                                <select id="DepartmentId" name="DepartmentId" class="form-control">
                                    <option value="">Select Department....</option>
                                    @foreach (var dept in ViewBag.Departments)
                                    {
                                        <option value="@dept.Id">@dept.Name</option>
                                    }
                                </select>
                                <br/>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="TeacherId">Teacher</label>
                            </td>
                            <td>
                                <select id="TeacherId" name="TeacherId" class="form-control">
                                    <option value="">Select Teacher....</option>
                                </select>
                                <br />
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label for="CreditTobeTaken">Credit To be Taken</label>
                            </td>
                            <td>
                                <input type="text" id="CreditTobeTaken" class="form-control" name="CreditTobeTaken" readonly="readonly" placeholder="This field is read only "/>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="CreditTaken">Remaing Credit</label>
                            </td>
                            <td>
                                <input type="text" id="CreditTaken" class="form-control" name="CreditTaken" readonly="readonly" placeholder="This field is read only " />
                                <br />
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label for="CourseId">Course</label>
                            </td>
                            <td>
                                <select id="CourseId" name="CourseId" class="form-control">
                                    <option value="">Select Course....</option>

                                </select>
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="Name">Name</label>
                            </td>
                            <td>
                                <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" placeholder="This field is read only " />
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="Credit">Credit</label>
                            </td>
                            <td>
                                <input type="text" id="Credit" class="form-control" name="Credit" readonly="readonly" placeholder="This field is read only " />
                                <br />
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <input type="submit" value="Assign" class="btn btn-success btn-block" id="submitButton" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>

        </div></div></div>
        <div class="col-sm-4"></div>


        @section Scripts {
            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>

            <script>
                $(document).ready(function () {
                    $('#submitButton').click(function () {
                        var val1 = parseFloat($('#CreditTaken').val());
                        var val2 = parseFloat($('#Credit').val());
                        var val = val1 - val2;
                        if (val < 0) {
                            var flag = confirm('Remaining credit is ' + val + '. Are you sure, you want to assign more credit?');
                            if (flag == false)
                                return false;
                        }
                        return true;
                    });

                    $("#courseAssignToteacher").validate({
                        rules: {

                            TeacherId: "required",

                            DepartmentId: "required",
                            CourseId: "required"
                        },
                        messages: {

                            TeacherId: "Please select the teacher Name!",

                            DepartmentId: "Please select department!",
                            CourseId: "Please select a Course!"
                        }
                    });

                    $("#DepartmentId").change(function () {
                        var deptId = $("#DepartmentId").val();
                        $("#TeacherId").empty();
                        $("#CourseId").empty();
                        $("#CourseId").append('<option value=' + "" + '>--Select Course--</option>');
                        $("#TeacherId").append('<option value=' + "" + '>--Select Teacher--</option>');
                        var json = { departmentId: deptId };

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetTeachersByDepartmentId", "CourseAssignToTeacher")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {

                                $.each(data, function (key, value) {
                                    //alert(key);
                                    $("#TeacherId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                                });
                            }
                        });

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetCoursesByDepartmentId", "CourseAssignToTeacher")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {

                                $.each(data, function (key, value) {

                                    $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');

                                });
                            }
                        });


                    });

                    //--------------show teacher information in textbx----

                    $("#TeacherId").change(function () {
                        var id = $("#TeacherId").val();

                        var json = { teacherId: id, };

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetTeacherById", "CourseAssignToTeacher")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {


                                var creditTakenTobeTaken = data.CreditTobeTaken;
                                var remainingCredit = (data.CreditTaken);
                                var creditT = creditTakenTobeTaken - remainingCredit;
                                $("#CreditTobeTaken").val(creditTakenTobeTaken);
                                $("#CreditTaken").val(creditT);


                            }
                        });


                    });
                    //-------------show Course information in textbx----

                    $("#CourseId").change(function () {
                        var id = $("#CourseId").val();
                        var json = { courseId: id }
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("GetCourseById", "CourseAssignToTeacher")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(json),
                            success: function (data) {
                                var name = data.Name;
                                var credit = data.Credit;
                                $("#Name").val(name);
                                $("#Credit").val(credit);

                            }
                        });


                    });


                });
            </script>
        }